# Copyright 2016  Chris Liechti <cliechti@gmx.net>
# SPDX-License-Identifier:    BSD-3-Clause

language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
#  - pypy

script:
  - python setup.py install
  - python setup.py flake8
#  - python test/test.py loop://
